#/bin/python

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... Find the sum of all the even-valued terms in the sequence which do not exceed four million.

import fib

mylist = [n for n in fib.fib(100) if n<4000000 and n%2==0]

print( mylist )  # [2, 8, 34, 144, 610, 2584, 10946, 46368, 196418, 832040, 3524578]

print( sum(mylist) ) # 4613732
