#/bin/python

# http://projecteuler.net/problem=44

'''
Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
'''

from itertools import count,combinations

def penta(maxn):
    for n in range(1,maxn+1):
        yield int(n*(3*n-1)/2)

cache = {1:1}
def is_penta(n):
    if n in cache: return cache[n]
    a,b,c = 3,-1,-2*n
    x = (b*-1 + (b**2-4*a*c)**0.5)/(2*a)
    cache[n] = x == int(x)
    return cache[n]

#print( is_penta(69) )
#print( is_penta(70) )
#print( is_penta(71) )
#print( is_penta(92) )
#print( is_penta(145) )

#print(list(penta(10)))
l = (n for n in penta(20000))
#print( l )

c = (n for n in combinations(l,2))
#cc = [n for n in c]
#print(len(c))
#cc = [n for n in c if n[0] in l and n[1] in l and (n[0]+n[1]) in l and (n[1]-n[0]) in l]
#cc = [n for n in c if (n[0]+n[1]) in l and (n[1]-n[0]) in l]
#cc = (n for n in c if (n[0]+n[1]) in l and (n[1]-n[0]) in l)
cc = (n for n in c if is_penta(n[0]+n[1]) and is_penta(n[1]-n[0]))

for n in cc:
    print(n,n[1]-n[0])
    break
